import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between items-center p-2 border-b-2 border-black">
          <h1>Demo Note</h1>
          <nav className="">
            <Link className="px-2" href="/lunch_menu">
              Lunch Menu
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
